spring:
  application:
    name: temperatura-client-feign

server:
  port: 9002
  servlet:    context-path: /conversor

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}